version: '3.8'

volumes:
  db_prod:
  static:
  media:
  nginx:

services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app/django_project
    volumes:
      - static:/app/django_project/static
      - media:/app/django_project/media
    command: 
      - sh
      - -c
      - |
        sleep 5s
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        gunicorn portal.wsgi:application --bind 0.0.0.0:8000      
    expose:
      - 8000
    env_file:
      - ./env/production/.env
    depends_on:
      - db  


  db:
    container_name: db
    image: postgres:14.3-alpine
    volumes:
      - db_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./env/production/.db.env
  

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static:/app/django_project/static
      - media:/app/django_project/media
      - ./nginx:/etc/nginx/conf.d/
    restart: always
