version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    working_dir: /app/backend 
    env_file:
      - ./env/development/.env
    ports:
      - "8000:8000"
      - "5678:5678"
    command:
      - sh
      - -c
      - |
        sleep 5s
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db


  db:
    image: postgres:14.3-alpine
    env_file:
      - ./env/development/.db.env
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./backend/db_dev:/var/lib/postgresql/data


  # mkdocs:
  #   build:
  #     context: .
  #     dockerfile: ./docker/MkDocs/Dockerfile
  #   working_dir: /app/wiki/generic
  #   container_name: mkdocs
  #   ports:
  #     - "8200:8200"
  #   command:
  #     - /bin/bash
  #     - -c
  #     - |
  #       mkdocs build
  #       mkdocs serve -a 0.0.0.0:8200
  #   volumes:
  #     - ./wiki/generic:/app/wiki/generic

  # jupyter:    
  #   working_dir: /app/backend
  #   command:
  #     - sh
  #     - -c
  #     - |
  #       sleep 30s
  #       python manage.py shell_plus --notebook
  #   container_name: jupyter
  #   extends:
  #     service: app
  #   ports:
  #     - "8888:8888"
  #   env_file:
  #     - ./env/development/.env
  #   depends_on:
  #     - web