version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app

  web:
    extends:
      service: app
    build: .
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - ./portal/env/development/.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    env_file:
      - ./portal/env/development/.db.env
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql/data


  jupyter:
    # build: ./jupyter
    command: python manage.py shell_plus --notebook
    # depends_on:
    #   - app
    extends:
      service: app
    ports:
      - "8888:8888"
    # volumes:
    #   - .:/jupyter
    env_file:
      - ./portal/env/development/.env
    environment:
      - DJANGO_SETTINGS_MODULE=portal._debug_settings
      - DJANGO_ALLOW_ASYNC_UNSAFE=true


# volumes:
#   postgres_data:
