version: '3.8'

services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app/django_project
    command: 
      - sh
      - -c
      - |
        sleep 10s
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        gunicorn portal.wsgi:application --bind 0.0.0.0:8000      
    ports:
      - 8000:8000
    env_file:
      - ./env/production/.env
    depends_on:
      - db  


  db:
    container_name: db
    image: postgres:14.3-alpine
    volumes:
      - ./django_project/db_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./env/production/.db.env
