version: '3.8'

services: 
  mkdocs:
    build:
      context: ../../
      dockerfile: ./docker/dockerfiles/MkDocs/Dockerfile
    working_dir: /app/wiki/generic
    # container_name: mkdocs
    ports:
      - "8200:8200"
    command:
      - /bin/bash
      - -c
      - |
        mkdocs build
        mkdocs serve -a 0.0.0.0:8200
    volumes:
      - ./wiki/generic:/app/wiki/generic
    tty: true